### ISSUE TITLE
Make this repo a template repository?

### ISSUE THREAD

**Issue by VenusianCat** [MarioTiscareno/sveltekit-personal-website#4]
Hi Mario! Not an issue, just a suggestion: perhaps consider making this repo a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository), as anyone that adopts this will likely be adding their own personal details that it wouldn't make sense to contribute back to core (as one might with a more traditional fork). 

Thanks again for sharing your work here!

**Comment by MarioTiscareno** [comment]
Hey Richard, I've enabled it as a template repository, thanks for the tip!

**Comment by MarioTiscareno** [comment]
Hey @VenusianCat, I've enabled it as a template repository, thanks for the tip!
